### ISSUE TITLE
Aurelia Server-Side Rendering: Use Cases

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/ssr-engine#1]
We need to determine use cases for server-side rendering and plan the SSR featureset accordingly. Currently, featureset must include:

 1. Aurelia-based routing - loading the correct view and viewModel for the given route.
 1. Support for pushState-based routes.
 1. View and viewModel state at server creation time.
 1. Binding and rendering handoff to client after server render.
 1. Server-only and client-only instructions (via a global flag, or contexts, or decorators, etc).

Nice to have:

 1. Multi-server support - node middleware, .NET core middleware, etc.

**Comment by EisenbergEffect** [comment]
I think we've got most of this now :)
