### ISSUE TITLE
Ruby backend engine

### ISSUE THREAD

**Issue by kubakrzempek** [aurelia/ssr-engine#10]
Hi Team!

I've read the Q1 report and found out you are looking for community members to help you extend the engine to other backend technologies. I happen to be a Ruby developer and would love to help you out with the integration. I don't have much experience with Aurelia (though I have 2 apps up and running in production), but hopefully, that won't be an issue.

Let me know what's your vision for moving this forward (of course, if you are interested).

Best regards,
Kuba

**Comment by Alexander-Taran** [comment]
Hmm interesting.
It will have to run node as well. I guess. Pretty much to render a page in Aurelia you'll have to execute it to the point of being rendered on server side.. and then give it back to client.
If that's feasible/desirable path.. Then it is definitely possible.
To your knowledge, are there more ruby developers interested in Aurelia?

**Comment by kubakrzempek** [comment]
Running node should not be an issue since it is common in Ruby/Rails apps nowadays to use it to compile assets anyway. I'll try to hack a middleware doing it. Should that be a separate repo?

Regarding Aurelia popularity among Ruby devs, I honestly don't know. There are many React/Angular/Vue related gems and tutorials which make those frameworks more popular in the community even though Aurelia arch seems to be more Ruby-friendly (to me at least). I've tried to advertise Aurelia to my colleagues which resulted in a few nods, but ultimately they've decided to proceed with more mainstream solutions. Maybe an SSR would be a little milestone here.

**Comment by EisenbergEffect** [comment]
@kubakrzempek Thanks for being willing to contribute. I can set up a repo here for you to issue a PR to. To clarify, will this be Rails-specific integration? If so, I can create `middleware-rails`. @JeroenVinke may have some thoughts on how to approach the integration.

**Comment by Alexander-Taran** [comment]
And community member Roland Quast @rquast had fiddled a lot with it.
You can reach him @ gitter or discourse

**Comment by kubakrzempek** [comment]
@EisenbergEffect I'd rather make it all-purpose without scoping the integration only to Rails, so Sinatra/Hanami/any Rack-like app user could benefit. :)

**Comment by EisenbergEffect** [comment]
I've created a repo here: https://github.com/aurelia/middleware-rack @JeroenVinke can provide some guidance on building out the middleware itself.

**Comment by Alexander-Taran** [comment]
@bigopon never happened..
